server: 
  port: 9527
 
spring: 
  application:
    name: spring-clound-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: spring-clound-dept
  prefix: /xbp
  ignored-services: "*"
  routes: 
    mydept.serviceId: spring-clound-dept
    mydept.path: /mydept/**
 
info:
  app.name: xbp-study-spring-clound
  company.name: www.xbp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

